# Knobs
- type: 'control_change'
  channel: 0
  note: null
  control: 74
  api_calls:
    - AdjustBrightness:
        host: 'http://localhost:8888'
        virtual_id: 'reactor-base-0'
# Buttons
- type: 'note_on'
  channel: 9
  note: 36
  control: null
  api_calls:
    - SwitchToEffectAndPreset:
        host: 'http://localhost:8888'
        virtual_id: 'reactor-base-0'
        category: 'ledfx_presets'
        effect_id: 'rainbow'
        preset_id: 'reset'
- type: 'note_on'
  channel: 9
  note: 37
  control: null
  api_calls:
    - SwitchToEffectAndPreset:
        host: 'http://localhost:8888'
        virtual_id: 'reactor-base-0'
        category: 'user_presets'
        effect_id: 'singleColor'
        preset_id: '1'
# Keyboard
- type: 'note_on'
  channel: 0
  note: 48
  control: null
  api_calls:
    - OneShot:
        host: 'http://localhost:8888'
        virtual_id: 'reactor-base-0'
        color: 'white'
    - OneShot:
        host: 'http://localhost:8888'
        virtual_id: 'reactor-base-1'
        color: 'red'
- type: 'note_on'
  channel: 0
  note: 49
  control: null
  api_calls:
    - OneShot:
        host: 'http://localhost:8888'
        virtual_id: 'reactor-base-0'
        color: 'yellow'
    - OneShot:
        host: 'http://localhost:8888'
        virtual_id: 'reactor-base-1'
        color: 'yellow'
