# Knobs
- type: 'control_change'
  channel: 0
  note: null
  control: 74
  api_calls:
    - AdjustBrightness:
        host: 'http://localhost:8888'
        virtual_id: 'main'
    - AdjustBrightness:
        host: 'http://localhost:8888'
        virtual_id: 'secondary'

# Buttons
- type: 'note_on'
  channel: 9
  note: 36
  control: null
  api_calls:
    - SwitchToEffectAndPreset:
        host: 'http://localhost:8888'
        virtual_id: 'main'
        category: 'user_presets'
        effect_id: 'strobe'
        preset_id: '1'  # This needs to be saved as '1' in LedFX
    - SwitchToEffectAndPreset:
        host: 'http://localhost:8888'
        virtual_id: 'secondary'
        category: 'user_presets'
        effect_id: 'bar'
        preset_id: '1'
- type: 'note_on'
  channel: 9
  note: 37
  control: null
  api_calls:
    - SwitchToEffectAndPreset:
        host: 'http://localhost:8888'
        virtual_id: 'main'
        category: 'user_presets'
        effect_id: 'bar'
        preset_id: '1'
    - SwitchToEffectAndPreset:
        host: 'http://localhost:8888'
        virtual_id: 'secondary'
        category: 'user_presets'
        effect_id: 'bar'
        preset_id: '1'

# Keyboard Oneshot
- type: 'note_on'
  channel: 0
  note: 48
  control: null
  api_calls:
    - OneShot:
        host: 'http://localhost:8888'
        virtual_id: 'main'
        color: 'white'
        ramp: 10
        hold: 0
        fade: 200
        brightness: 1.0
    - OneShot:
        host: 'http://localhost:8888'
        virtual_id: 'secondary'
        color: 'red'
        ramp: 10
        hold: 0
        fade: 200
        brightness: 1.0

# Keyboard Ripple
- type: 'note_on'
  channel: 0
  note: 55
  control: null
  api_calls:
    - Ripple:
        host: 'http://localhost:8888'
        virtual_id: 'main'
        color: 'white'
        ramp: 10
        hold: 0
        fade: 3000
        probability: 0.1
        brightness: 1.0
    - Ripple:
        host: 'http://localhost:8888'
        virtual_id: 'secondary'
        color: 'yellow'
        ramp: 10
        hold: 0
        fade: 3000
        probability: 0.1
        brightness: 1.0

# Keyboard Wave
- type: 'note_on'
  channel: 0
  note: 65
  control: null
  api_calls:
    - Wave:
        host: 'http://localhost:8888'
        virtual_id: 'main'
        color: 'white'
        pixel_step: 5
        timestep: 0.05
        brightness: 1.0
    - Wave:
        host: 'http://localhost:8888'
        virtual_id: 'secondary'
        color: 'yellow'
        pixel_step: 5
        timestep: 0.05
        brightness: 1.0

# Keyboard Slow Wave
- type: 'note_on'
  channel: 0
  note: 72
  control: null
  api_calls:
    - Wave:
        host: 'http://localhost:8888'
        virtual_id: 'main'
        color: 'white'
        pixel_step: 2
        timestep: 0.05
        brightness: 1.0
    - Wave:
        host: 'http://localhost:8888'
        virtual_id: 'secondary'
        color: 'white'
        pixel_step: 2
        timestep: 0.05
        brightness: 1.0
